ci: exit with error if failed to fetch version or release number

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -10,7 +10,7 @@ jobs:
     steps:
       - uses: actions/checkout@v6
 
-      - name: Fetch release version
+      - name: Fetch version release
         run: |
             VERSION_RELEASE=$(curl -s https://archive.synology.com/download/Utility/SynologyDriveClient | grep -oP '\d+\.\d+\.\d+-\d+' | head -n 1)
 
@@ -19,6 +19,11 @@ jobs:
 
             RELEASE=$(echo $VERSION_RELEASE | cut -d'-' -f2)
             echo "RELEASE=$RELEASE" >> "$GITHUB_ENV"
+
+            if [[ -z $VERSION || -z $RELEASE ]]; then
+              echo "Error: failed to fetch the latest version or release number." >&2
+              exit 1
+            fi
 
       - name: Modify files
         run: |
